apiVersion: ramendr.openshift.io/v1alpha1
kind: Recipe
metadata:
  name: busybox-discovered-rbd-hook
spec:
  appType: busybox
  groups:
  - backupRef: busybox-discovered-rbd-hook
    excludedResourceTypes:
    - events
    - event.events.k8s.io
    - persistentvolumes
    - replicaset
    - persistentvolumeclaims
    - pods
    includedNamespaces:
    - busybox-discovered-rbd-hook
    labelSelector:
      matchExpressions:
      - key: appname
        operator: In
        values:
        - busybox
    name: busybox-discovered-rbd-hook
    type: resource
  workflows:
  - failOn: any-error
    name: backup
    sequence:
    - hook: deployment-check/stateReady
    - group: busybox-discovered-rbd-hook
  - failOn: any-error
    name: restore
    sequence:
    - group: busybox-discovered-rbd-hook
    - hook: deployment-check/stateReady
  hooks:
  - name: deployment-check
    type: check
    namespace: busybox-discovered-rbd-hook
    selectResource: deployment
    nameSelector: busybox
    timeout: 800
    onError: fail
    chks:
    - name: stateReady
      timeout: 900
      onError: fail
      condition: "{$.spec.replicas} == {$.status.readyReplicas}"
  volumes:
    includedNamespaces:
    - busybox-discovered-rbd-hook
    name: varlog
    type: volume
    labelSelector:
      matchExpressions:
      - key: appname
        operator: In
        values:
        - busybox
