---
resources:
  - ../base
patches:
  # Customize for internal RBD storage.
  - target:
      kind: PersistentVolumeClaim
      name: busybox-pvc-1
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: ocs-storagecluster-ceph-rbd
  - target:
      kind: PersistentVolumeClaim
      name: busybox-pvc-2
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: ocs-storagecluster-ceph-rbd
  - target:
      kind: PersistentVolumeClaim
      name: busybox-pvc-3
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: ocs-storagecluster-ceph-rbd
  - target:
      kind: PersistentVolumeClaim
      name: busybox-pvc-4
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: ocs-storagecluster-ceph-rbd

